### ISSUE TITLE
RyzenAdj exposes more features than we do

### ISSUE THREAD

**Issue by pastaq** [ShadowBlip/PowerStation#4]
We only expose a small selection of capabilities that RyzenAdj provides. Recently some of the more esoteric features have been found to be beneficial on newer devices, such as APU Skin temp on the Legion Go. We should expose everything RyzenAdj can do.

**Comment by NeroReflex** [comment]
Provided the GUI takes advantage of the unsupported error I introduced to avoid a hard lock-in in ryzenadj

**Comment by pastaq** [comment]
RyzenAdj reliance should be minimized as a last resort.
